# Especialització de DataScience de la IT ACADEMY
### *Sprint2 - Tasca 2 - Exercici 1*
#### **Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.**

#### Alumne: Jorge Prieto Data: 10/02/2022

In [2]:
import numpy as np

In [3]:
arr = np.array([12,72,11,0,-3,31,2,1,67,15], dtype='int64')
print(arr)

[12 72 11  0 -3 31  2  1 67 15]


In [4]:
print(arr.dtype)

int64


In [5]:
print("l'array es de dimensió",arr.ndim) #dimensió de l'array

l'array es de dimensió 1


### *Sprint2 - Tasca 2 - Exercici 2*
#### **De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.**

In [6]:
print("la mitja del valors de l'array es",arr.mean())

la mitja del valors de l'array es 20.8


In [7]:
print("la mitjana del valors de l'array es",np.median(arr))

la mitjana del valors de l'array es 11.5


In [8]:
print("la resta de la mitja i la mitjana es",(arr.mean()-np.median(arr)))

la resta de la mitja i la mitjana es 9.3


### *Sprint2 - Tasca 2 - Exercici 3*
#### **Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.**

In [9]:
arr = np.random.randint(100,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 0 i 99
print(arr)

[[31 89 23 19 42]
 [97  3 41 41 10]
 [37 79 67 75 22]
 [39 60 10 93  4]
 [66 64 20 88 33]]


In [10]:
print("El valor màxim de la matriu es",np.amax(arr))

El valor màxim de la matriu es 97


In [11]:
count = 0
for x in arr:
    count +=1
    print("fila",count,":",x," - Valor Màxim ",np.amax(x))

fila 1 : [31 89 23 19 42]  - Valor Màxim  89
fila 2 : [97  3 41 41 10]  - Valor Màxim  97
fila 3 : [37 79 67 75 22]  - Valor Màxim  79
fila 4 : [39 60 10 93  4]  - Valor Màxim  93
fila 5 : [66 64 20 88 33]  - Valor Màxim  88


In [12]:
arrTranspose = np.transpose(arr) #Trasposar la matriu per simplicar el print de les columnes

In [13]:
count = 0
for y in arrTranspose:
    count +=1
    print("columna",count,":",y," - Valor Màxim ",np.amax(y))

columna 1 : [31 97 37 39 66]  - Valor Màxim  97
columna 2 : [89  3 79 60 64]  - Valor Màxim  89
columna 3 : [23 41 67 10 20]  - Valor Màxim  67
columna 4 : [19 41 75 93 88]  - Valor Màxim  93
columna 5 : [42 10 22  4 33]  - Valor Màxim  42


### *Sprint2 - Tasca 2 - Exercici 4*
#### **Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".**

In [14]:
array1 = np.random.randint(100,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 0 i 99
array2 = np.random.randint(100,size=(5, 5))
print("Array1:")
print(array1)
print("Array2:")
print(array2)

Array1:
[[14 59 92 59 91]
 [ 9 79 32 42 55]
 [97 27 40 23 19]
 [37 25 65 96 59]
 [83 70 52 21 14]]
Array2:
[[64 12  3  9 20]
 [41 85 32 40 58]
 [90 41 65 55 62]
 [53 31 41 64 45]
 [83 24 85 51 61]]


In [15]:
print("Multiplicació de matrius de igual index")
print(array1 * array2)
print("\nSuma de matrius de igual index")
print(array1 + array2)

Multiplicació de matrius de igual index
[[ 896  708  276  531 1820]
 [ 369 6715 1024 1680 3190]
 [8730 1107 2600 1265 1178]
 [1961  775 2665 6144 2655]
 [6889 1680 4420 1071  854]]

Suma de matrius de igual index
[[ 78  71  95  68 111]
 [ 50 164  64  82 113]
 [187  68 105  78  81]
 [ 90  56 106 160 104]
 [166  94 137  72  75]]


In [16]:
print("Multiplicació de matriu per valor 25")
print(array1 * 25)
print("Suma de matriu per valor 25")
print(array1 + 25)

Multiplicació de matriu per valor 25
[[ 350 1475 2300 1475 2275]
 [ 225 1975  800 1050 1375]
 [2425  675 1000  575  475]
 [ 925  625 1625 2400 1475]
 [2075 1750 1300  525  350]]
Suma de matriu per valor 25
[[ 39  84 117  84 116]
 [ 34 104  57  67  80]
 [122  52  65  48  44]
 [ 62  50  90 121  84]
 [108  95  77  46  39]]


In [17]:
array3 = np.random.randint(100,size=(1, 5))
print("Array3:")
print(array3)

Array3:
[[85 66 68 39 39]]


In [18]:
print("Multiplicació de matriu1 per matriu3 amb index unitari")
print(array1 * array3)
print("Suma de matriu1 per matriu3 amb index unitari")
print(array1 + array3)

Multiplicació de matriu1 per matriu3 amb index unitari
[[1190 3894 6256 2301 3549]
 [ 765 5214 2176 1638 2145]
 [8245 1782 2720  897  741]
 [3145 1650 4420 3744 2301]
 [7055 4620 3536  819  546]]
Suma de matriu1 per matriu3 amb index unitari
[[ 99 125 160  98 130]
 [ 94 145 100  81  94]
 [182  93 108  62  58]
 [122  91 133 135  98]
 [168 136 120  60  53]]


### *Sprint2 - Tasca 2 - Exercici 5*
#### **Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.**

In [19]:
count = 0;
for fila in array1:
    count +=1
    print("Fila",count,":",fila)

Fila 1 : [14 59 92 59 91]
Fila 2 : [ 9 79 32 42 55]
Fila 3 : [97 27 40 23 19]
Fila 4 : [37 25 65 96 59]
Fila 5 : [83 70 52 21 14]


In [20]:
#Suma fila 1 i 3
print("Fila fileres 1 i 3:",array1[0]+array1[2])

Fila fileres 1 i 3: [111  86 132  82 110]


In [21]:
#Accés a elements de la matriu
print('2n element de la 1ra fila:',array1[0,1])
print("5è element de la 4ra fila:",array1[3,4])

2n element de la 1ra fila: 59
5è element de la 4ra fila: 59


### *Sprint2 - Tasca 2 - Exercici 6*
#### **Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.**
#### **Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.**

In [22]:
array1

array([[14, 59, 92, 59, 91],
       [ 9, 79, 32, 42, 55],
       [97, 27, 40, 23, 19],
       [37, 25, 65, 96, 59],
       [83, 70, 52, 21, 14]])

In [23]:
#Màscara retorna true si la divisió entre 4 dona un enter
mask = (array1 % 4)==0
mask

array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False]])

In [24]:
#Màscara retorna resta de la divisió entre 4
mask1 = (array1 % 4)
mask1

array([[2, 3, 0, 3, 3],
       [1, 3, 0, 2, 3],
       [1, 3, 0, 3, 3],
       [1, 1, 1, 0, 3],
       [3, 2, 0, 1, 2]], dtype=int32)

### *Sprint2 - Tasca 2 - Exercici 7*
#### **A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.**

In [25]:
array1

array([[14, 59, 92, 59, 91],
       [ 9, 79, 32, 42, 55],
       [97, 27, 40, 23, 19],
       [37, 25, 65, 96, 59],
       [83, 70, 52, 21, 14]])

In [26]:
#Matriu indexada amb la màscara. Retorna els valors on es compleix la màscara
array1[mask]

array([92, 32, 40, 96, 52])