# Especialització de DataScience de la IT ACADEMY
#### *Sprint2 - Tasca 2 - Exercici 6*
#### **Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.**
#### **Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.**

#### Alumne: Jorge Prieto Data: 12/02/2022

In [54]:
import numpy as np

In [69]:
array1 = np.random.randint(1,33,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 1 i 32
array1

array([[27,  3, 26, 32, 16],
       [ 3,  3, 30, 28, 32],
       [27, 17, 11, 14, 25],
       [27, 18, 32, 24,  9],
       [ 3, 23,  5,  1, 17]])

In [74]:
#Màscara retorna true si la divisió entre 4 dona un enter
mask = (array1 % 4)==0
mask

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [76]:
#Màscara retorna resta de la divisió entre 4
mask1 = (array1 % 4)
mask1

array([[3, 3, 2, 0, 0],
       [3, 3, 2, 0, 0],
       [3, 1, 3, 2, 1],
       [3, 2, 0, 0, 1],
       [3, 3, 1, 1, 1]], dtype=int32)

In [77]:
#Retorna els valors on es compleix la màscara
array1[mask]

array([32, 16, 28, 32, 32, 24])