# Especialització de DataScience de la IT ACADEMY
#### *Sprint2 - Tasca 2 - Exercici 5*
#### **Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.**

#### Alumne: Jorge Prieto Data: 12/02/2022

In [48]:
import numpy as np

In [49]:
array1 = np.random.randint(100,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 0 i 99
print("Array1:")
print(array1)

Array1:
[[31 94 97  6 76]
 [74 54 90 61 92]
 [83 87 55 77 59]
 [36 38 77 39 85]
 [34 18 11 27 57]]


In [50]:
print("Fila 1:",array1[0])
print("Fila 2:",array1[1])
print("Fila 3:",array1[2])
print("Fila 4:",array1[3])
print("Fila 5:",array1[4])

Fila 1: [31 94 97  6 76]
Fila 2: [74 54 90 61 92]
Fila 3: [83 87 55 77 59]
Fila 4: [36 38 77 39 85]
Fila 5: [34 18 11 27 57]


In [51]:
count = 0;
for fila in array1:
    count +=1
    print("Fila",count,":",fila)

Fila 1 : [31 94 97  6 76]
Fila 2 : [74 54 90 61 92]
Fila 3 : [83 87 55 77 59]
Fila 4 : [36 38 77 39 85]
Fila 5 : [34 18 11 27 57]


In [52]:
#Suma fila 1 i 3
print("Fila fileres 1 i 3:",array1[0]+array1[2])

Fila fileres 1 i 3: [114 181 152  83 135]


In [53]:
#Accés a elements de la matriu
print('2n element de la 1ra fila:',array1[0,1])
print("5è element de la 4ra fila:",array1[3,4])

2n element de la 1ra fila: 94
5è element de la 4ra fila: 85
