# Especialització de DataScience de la IT ACADEMY
#### *Sprint2 - Tasca 2 - Exercici 3*
#### **Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.**

#### Alumne: Jorge Prieto Data: 10/02/2022

In [41]:
import numpy as np

In [81]:
arr = np.random.randint(100,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 0 i 99
print(arr)

[[12 36 89 79 64]
 [60  7 44 95 24]
 [70 15 27 38 84]
 [34 86 43 67 95]
 [94 90 98 34 73]]


In [82]:
print("El valor màxim de la matriu es",np.amax(arr))

El valor màxim de la matriu es 98


In [109]:
count = 0
for x in arr:
    count +=1
    print("fila",count,":",x," - Valor Màxim ",np.amax(x))

fila 1 : [12 36 89 79 64]  - Valor Màxim  89
fila 2 : [60  7 44 95 24]  - Valor Màxim  95
fila 3 : [70 15 27 38 84]  - Valor Màxim  84
fila 4 : [34 86 43 67 95]  - Valor Màxim  95
fila 5 : [94 90 98 34 73]  - Valor Màxim  98


In [104]:
arrTranspose = np.transpose(arr) #Trasposar la matriu per simplicar el print de les columnes

In [110]:
count = 0
for y in arrTranspose:
    count +=1
    print("columna",count,":",y," - Valor Màxim ",np.amax(y))

columna 1 : [12 60 70 34 94]  - Valor Màxim  94
columna 2 : [36  7 15 86 90]  - Valor Màxim  90
columna 3 : [89 44 27 43 98]  - Valor Màxim  98
columna 4 : [79 95 38 67 34]  - Valor Màxim  95
columna 5 : [64 24 84 95 73]  - Valor Màxim  95
