# Especialització de DataScience de la IT ACADEMY
#### *Sprint2 - Tasca 2 - Exercici 7*
#### **A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.**

#### Alumne: Jorge Prieto Data: 12/02/2022

In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(1,33,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 1 i 32
array1

array([[ 9, 19,  3,  5, 13],
       [22, 19, 21,  7, 12],
       [ 2, 32, 12, 18, 28],
       [11, 21, 32, 21, 18],
       [ 8, 23,  7, 26, 28]])

In [3]:
#Màscara retorna true si la divisió entre 4 dona un enter
mask = (array1 % 4)==0
mask

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False,  True,  True, False,  True],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [4]:
#Màscara retorna resta de la divisió entre 4
mask1 = (array1 % 4)
mask1

array([[1, 3, 3, 1, 1],
       [2, 3, 1, 3, 0],
       [2, 0, 0, 2, 0],
       [3, 1, 0, 1, 2],
       [0, 3, 3, 2, 0]], dtype=int32)

In [6]:
#Matriu indexada amb la màscara. Retorna els valors on es compleix la màscara
array1[mask]

array([12, 32, 12, 28, 32,  8, 28])