# Especialització de DataScience de la IT ACADEMY
#### *Sprint2 - Tasca 2 - Exercici 4*
#### **Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".**

#### Alumne: Jorge Prieto Data: 12/02/2022

In [3]:
import numpy as np

In [8]:
array1 = np.random.randint(100,size=(5, 5)) #Crea un array de 5x5 amb valors enters aleatoris compresos entre 0 i 99
array2 = np.random.randint(100,size=(5, 5))
print("Array1:")
print(array1)
print("Array2:")
print(array2)

Array1:
[[81 12 35 55 12]
 [ 5 54 29  6  1]
 [28 55  3  2 84]
 [37  3 82 86 64]
 [38 95  0  4  6]]
Array2:
[[ 7 75 49 13 65]
 [94 38  3 93  8]
 [13 27 90 78 21]
 [12 73 46  7 62]
 [28 98 94 36 17]]


In [11]:
print("Multiplicació de matrius de igual index")
print(array1 * array2)
print("\nSuma de matrius de igual index")
print(array1 + array2)

Multiplicació de matrius de igual index
[[ 567  900 1715  715  780]
 [ 470 2052   87  558    8]
 [ 364 1485  270  156 1764]
 [ 444  219 3772  602 3968]
 [1064 9310    0  144  102]]

Suma de matrius de igual index
[[ 88  87  84  68  77]
 [ 99  92  32  99   9]
 [ 41  82  93  80 105]
 [ 49  76 128  93 126]
 [ 66 193  94  40  23]]


In [12]:
print("Multiplicació de matriu per valor 25")
print(array1 * 25)
print("Suma de matriu per valor 25")
print(array1 + 25)

Multiplicació de matriu per matriu unitaria
[[2025  300  875 1375  300]
 [ 125 1350  725  150   25]
 [ 700 1375   75   50 2100]
 [ 925   75 2050 2150 1600]
 [ 950 2375    0  100  150]]

Suma de matrius de matriu per matriu unitaria
[[106  37  60  80  37]
 [ 30  79  54  31  26]
 [ 53  80  28  27 109]
 [ 62  28 107 111  89]
 [ 63 120  25  29  31]]


In [23]:
array3 = np.random.randint(100,size=(1, 5))
print("Array3:")
print(array3)

Array3:
[[81  4 93  7 48]]


In [25]:
print("Multiplicació de matriu1 per matriu3 amb index unitari")
print(array1 * array3)
print("Suma de matriu1 per matriu3 amb index unitari")
print(array1 + array3)

Multiplicació de matriu1 per matriu3 amb index unitari
[[6561   48 3255  385  576]
 [ 405  216 2697   42   48]
 [2268  220  279   14 4032]
 [2997   12 7626  602 3072]
 [3078  380    0   28  288]]
Suma de matriu1 per matriu3 amb index unitari
[[162  16 128  62  60]
 [ 86  58 122  13  49]
 [109  59  96   9 132]
 [118   7 175  93 112]
 [119  99  93  11  54]]
